### ISSUE TITLE
{ci} Warning when linking debug test on macOS

### ISSUE THREAD

**Issue by asmaloney** [asmaloney/libE57Format#123] opened 2022-10-09 16:27 UTC
With the new testing, we're getting warnings when linking debug test on macOS (not getting them w/release):

> ld: warning: direct access in function 'e57::BlobNodeImpl::dump(int, std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const' from file 'libE57Format-d.a(BlobNodeImpl.cpp.o)' to global weak symbol 'std::__1::basic_ostream<char, std::__1::char_traits<char> >& std::__1::endl<char, std::__1::char_traits<char> >(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)' from file 'lib/libgtest.a(gtest-all.cc.o)' means the weak symbol cannot be overridden at runtime. This was likely caused by different translation units being compiled with different visibility settings.

This happens on the CI, but not when I build locally.

**Comment by ptc-jhoerner** [comment] 2022-10-31 16:52
This sort of problems can be usually fixed by setting CMAKE_VISIBILITY_INLINES_HIDDEN to ON and CMAKE_<LANG>_VISIBILITY_PRESET to hidden everywhere in the build. Looks like Release probably does that (maybe implicitly), but Debug doesn't.

**Comment by asmaloney** [comment] 2022-10-31 19:10
I think it's this: `CMAKE_VISIBILITY_INLINES_HIDDEN`

Thanks Jiri. Still strange that I don't see it locally.

**Closed** 2022-10-31 19:40 UTC

**Comment by ptc-jhoerner** [comment] 2022-10-31 19:41
Usually one wants to set both consistently, they are different options setting `-fvisibility=hidden` and `-fvisibility-inlines-hidden`. In Xcode build settings you can see them as "Symbols Hidden by Default" and "Inline Methods Hidden".

I think the applied settings might differ between Xcode and ninja if this is not set explicitly from CMake. If you use Xcode generator I wouldn't be surprised you don't see it.

Maybe the problem is here: 
https://github.com/asmaloney/libE57Format/blob/0626bbf8d3f2a29e9ae9039e20c0f5cb5df34354/CMakeLists.txt#L207
here we override the visibility for testing, but `E57_VISIBILITY_HIDDEN` is by default ON so the tests set hidden visibility here:
https://github.com/asmaloney/libE57Format/blob/d196939a431ab3424e907f5ec97b551ef26ac843/test/CMakeLists.txt#L23 

So there is indeed a mixed visibility. I agree all these places should set also `CMAKE_VISIBILITY_INLINES_HIDDEN`, these 2 settings should really go together.

**Comment by asmaloney** [comment] 2022-10-31 19:47
> these 2 settings should really go together

Yes - I think that's the mistake. When it was added only `CXX_VISIBILITY_PRESET` was set so when I overrode it in the test I wasn't aware of `CMAKE_VISIBILITY_INLINES_HIDDEN`.

Thanks (again) for pointing me in the right direction. I've never used these settings before.

(I'm actually not using Xcode  - I build with Qt Creator which is using CMake. Regardless - fixed now!)
